# Replace with your own pack id or keep to continue using the default
#
# Pack id can be found under "Your packs" @ https://cosmo.senseiju.me
pack-id: a939f783-3711-48ee-b2f5-69f66efcd1c2

# Setting this to true will mean that models will not show UNLESS the player is wearing a helmet
# This could be useful if you want players to distinguish between
require-helmets: false

# By default, the plugin does as much of its actions async to help reduce server load although it is
# not a significant increase in performance until your running into the 100's of players.
# However, if you are having issues with the plugin being buggy and not working as intended, you
# can try set this to 'false' and see if anything improves
use-async: true

# Internal http server to deliver the pack
#
# By default, the internal server will not be used and your pack will be provided by the Cosmo servers.
# By doing so, if the pack is updated whilst the server is live, it will cause the next players to login to receive
# a more up to date pack and previously logged in players must re-log. Using the internal server is ideal as it will
# prevent the de-sync.
use-internal-http-server: false

# You may need to change this port if it interferes with any other applications installed on the machine.
# Make sure to also port forward.
internal-http-port: 12345

# Set to true to deliver content from the development server
development-server: false